replicaCount: 1

image:
  # customise this to your own repository
  repository: docker.io/joelofelectronics/llm-agent-app
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

env:
  inngestEnv: "prod"
  inngestAppId: "llm-agent-app"
  
secrets:
  inngestSecretName: "inngest-secrets"
  redisSecretName: "redis-secrets"