ollama:
  gpu:
    # -- Enable GPU integration (disabled for CPU-only deployment)
    enabled: false
    # -- Specify the number of GPU to 1 (not used when enabled=false)
    number: 1
    
persistentVolume:
  enabled: true
  size: 100Gi


